#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';

use MojoGolf::DB::Challenge;
use MojoGolf::DB::ChallengeData;

my $challenge = MojoGolf::DB::Challenge->new(name => "uppercase_vowels",
                                             descr=> qq{
<p>The input data (line based) should be output as-is, except all voweles
should be forced to upper-case.</p>
})->save();

my $data = MojoGolf::DB::ChallengeData->new(
  challenge_id => $challenge->id,
  input => qq{
Praesent sit amet malesuada massa. Praesent sollicitudin metus massa, ut varius tellus pharetra in.
Maecenas posuere semper nibh, et ullamcorper mauris consectetur in. Donec non accumsan libero, eu
ultricies justo. Etiam sapien lacus, iaculis a tincidunt sed, commodo eu elit. Phasellus posuere
nec nisl in semper. Integer aliquet sagittis mattis. Sed sed eleifend leo, vel pretium lacus.
Vivamus nisi lacus, porta et justo in, elementum commodo magna. Vivamus sagittis at lectus eget
pretium. Maecenas tempor ante vel nunc fermentum malesuada. Nam consectetur ante vel enim
scelerisque, vitae pulvinar quam volutpat. Integer fringilla sodales quam, placerat aliquam lacus
facilisis non. Maecenas at consectetur quam.
},
  output => qq{
PrAEsEnt sIt AmEt mAlEsUAdA mAssA. PrAEsEnt sOllIcItUdIn mEtUs mAssA, Ut vArIUs tEllUs phArEtrA In.
MAEcEnAs pOsUErE sEmpEr nIbh, Et UllAmcOrpEr mAUrIs cOnsEctEtUr In. DOnEc nOn AccUmsAn lIbErO, EU
UltrIcIEs jUstO. EtIAm sApIEn lAcUs, IAcUlIs A tIncIdUnt sEd, cOmmOdO EU ElIt. PhAsEllUs pOsUErE
nEc nIsl In sEmpEr. IntEgEr AlIqUEt sAgIttIs mAttIs. SEd sEd ElEIfEnd lEO, vEl prEtIUm lAcUs.
VIvAmUs nIsI lAcUs, pOrtA Et jUstO In, ElEmEntUm cOmmOdO mAgnA. VIvAmUs sAgIttIs At lEctUs EgEt
prEtIUm. MAEcEnAs tEmpOr AntE vEl nUnc fErmEntUm mAlEsUAdA. NAm cOnsEctEtUr AntE vEl EnIm
scElErIsqUE, vItAE pUlvInAr qUAm vOlUtpAt. IntEgEr frIngIllA sOdAlEs qUAm, plAcErAt AlIqUAm lAcUs
fAcIlIsIs nOn. MAEcEnAs At cOnsEctEtUr qUAm.
})->save();
  
my $language = MojoGolf::DB::Language->new(
  name => 'perl',
  compile => 'perl -cw $1',
  run     => 'perl $1',
)->save();
  
